version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo "Pre-build stage..."

  build:
    commands:
      - echo "Build stage..."
      - sam build -t template.yml

  post_build:
    commands:
      - echo "Post-build stage..."
      - sam deploy --stack-name ${STACK_NAME} --region ${AWS_REGION} --s3-bucket ${S3_BUCKET} --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --parameter-overrides DatabaseHostnameReader=${DB_HOSTNAME_READER} DatabaseHostnameWriter=${DB_HOSTNAME_WRITER} DatabaseUsername=${DB_USERNAME} DatabasePassword=${DB_PASSWORD} DatabaseName=${DB_NAME} DatabasePort=${DB_PORT} SecurityGroup=${SECURITY_GROUP} Subnet1=${SUBNET_1} Subnet2=${SUBNET_2} Subnet3=${SUBNET_3}




